/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.awt.Component;
import java.text.NumberFormat;
import java.text.ParseException;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.Collections;
import java.util.List;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;
import model.ControleFinanceiro;
import model.Despesa;
import model.Pessoa;
import model.Receita;
import model.TipoDespesa;
import model.TipoReceita;

/**
 *
 * @author Amanda Miranda Zanella, Bruno Henrique Wiedemann Reis, Lucas Miguel
 * Vieira, Matheus Guilherme Jacinto
 */
public class ControleFinanceiroUI extends javax.swing.JFrame {

    ControleFinanceiro control = new ControleFinanceiro();

    /**
     * construtor
     */
    public ControleFinanceiroUI() {
        initComponents();
        jtTabela.getTableHeader().setReorderingAllowed(false);
        this.getContentPane().setBackground(Color.black);
        formatCdata();//chama o metodo que aplica a mask no campo de data
        this.setVisible(true);

        LocalDateTime agora = LocalDateTime.now();//pega a data de agora
        DateTimeFormatter formatarData = DateTimeFormatter.ofPattern("dd/MM/yyyy");//define o formato da data
        String dataFormatada = formatarData.format(agora);//aplica a data no formato 
        jlData.setText("Data : " + dataFormatada);//exibe a data atual na tela

        boolean validacao = false;
        PessoaUI pessoaUI = new PessoaUI(null, true);//tela para pergutar o nome
        while (validacao == false) {//loop para pegar o nome do usuario , garante que o usuario não continue até informar um nome valido

            pessoaUI.setVisible(true);

            Pessoa p = pessoaUI.getPessoa();
            if (p.getNome() == null) {

            } else {
                validacao = true;
                control.setPessoa(p);
            }
        }

        jlNome.setText("Controle financeiro de " + control.getPessoa().getNome());
        rbAlimentacao.setEnabled(false);
        rbTransporte.setEnabled(false);
        rbResidencia.setEnabled(false);
        rbSaude.setEnabled(false);
        rbEducacao.setEnabled(false);
        rbEntretenimento.setEnabled(false);
        rbOutrosD.setEnabled(false);

    }

    /**
     *metodo para formatar o campo data da forma desejada
     */
    public final void formatCdata() {
        try {
            MaskFormatter mask = new MaskFormatter("##/##/####");//define o formato da marcara 
            mask.install(tfData);//aplica a mascara ao text field data
        } catch (ParseException e) {

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgpTipoControle = new javax.swing.ButtonGroup();
        brgpTipoDespesa = new javax.swing.ButtonGroup();
        brgpTipoReceita = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jlNome = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtTabela = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        rbAlimentacao = new javax.swing.JRadioButton();
        rbTransporte = new javax.swing.JRadioButton();
        rbResidencia = new javax.swing.JRadioButton();
        rbSaude = new javax.swing.JRadioButton();
        rbEducacao = new javax.swing.JRadioButton();
        rbEntretenimento = new javax.swing.JRadioButton();
        rbOutrosD = new javax.swing.JRadioButton();
        jblTiposDeDespesa = new javax.swing.JLabel();
        rbDespesa = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        rbSalario = new javax.swing.JRadioButton();
        rbDecimo = new javax.swing.JRadioButton();
        rbFerias = new javax.swing.JRadioButton();
        rbOutrosR = new javax.swing.JRadioButton();
        jlbTiposDeReceita = new javax.swing.JLabel();
        rbReceita = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        jlbValor = new javax.swing.JLabel();
        tfValor = new javax.swing.JTextField();
        jlbData = new javax.swing.JLabel();
        tfData = new javax.swing.JFormattedTextField();
        jbInserir = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jlSaldoAtual = new javax.swing.JLabel();
        jlSaldoTotal = new javax.swing.JLabel();
        jlData = new javax.swing.JLabel();
        jbMudarNome = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jbDespesas = new javax.swing.JButton();
        jbReceitas = new javax.swing.JButton();
        jbReceitaDespesa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CONTROLE FINANCEIRO");
        setBackground(new java.awt.Color(204, 204, 204));
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.darkGray, null));

        jlNome.setBackground(new java.awt.Color(204, 204, 255));
        jlNome.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jlNome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlNome.setText("Controle Financeiro de ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlNome, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                .addGap(11, 11, 11))
        );

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, null));

        jtTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo de Lançamento", "Tipo", "Valor", "Data"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtTabela);

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        brgpTipoDespesa.add(rbAlimentacao);
        rbAlimentacao.setText("Alimentação");
        rbAlimentacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAlimentacaoActionPerformed(evt);
            }
        });

        brgpTipoDespesa.add(rbTransporte);
        rbTransporte.setText("Transporte");

        brgpTipoDespesa.add(rbResidencia);
        rbResidencia.setText("Residência");

        brgpTipoDespesa.add(rbSaude);
        rbSaude.setText("Saúde");

        brgpTipoDespesa.add(rbEducacao);
        rbEducacao.setText("Educação");

        brgpTipoDespesa.add(rbEntretenimento);
        rbEntretenimento.setText("Entretenimento");

        brgpTipoDespesa.add(rbOutrosD);
        rbOutrosD.setText("Outras");
        rbOutrosD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbOutrosDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(rbEntretenimento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rbOutrosD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rbEducacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rbSaude, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rbResidencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rbTransporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rbAlimentacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbAlimentacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbTransporte)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbResidencia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbSaude)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbEducacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbEntretenimento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbOutrosD)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jblTiposDeDespesa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jblTiposDeDespesa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblTiposDeDespesa.setText("Tipos de despesa");
        jblTiposDeDespesa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btgpTipoControle.add(rbDespesa);
        rbDespesa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rbDespesa.setText("Despesa");
        rbDespesa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rbDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDespesaActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        brgpTipoReceita.add(rbSalario);
        rbSalario.setText("Salário");

        brgpTipoReceita.add(rbDecimo);
        rbDecimo.setText("Décimo terceiro");

        brgpTipoReceita.add(rbFerias);
        rbFerias.setText("Férias");

        brgpTipoReceita.add(rbOutrosR);
        rbOutrosR.setText("Outras");
        rbOutrosR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbOutrosRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(rbDecimo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rbOutrosR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rbFerias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rbSalario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbSalario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbDecimo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbFerias)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbOutrosR)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jlbTiposDeReceita.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlbTiposDeReceita.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbTiposDeReceita.setText("Tipos de receita");
        jlbTiposDeReceita.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btgpTipoControle.add(rbReceita);
        rbReceita.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rbReceita.setSelected(true);
        rbReceita.setText("Receita");
        rbReceita.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rbReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbReceitaActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(204, 204, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel6.setForeground(new java.awt.Color(255, 153, 255));

        jlbValor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlbValor.setText("Valor:");

        tfValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfValorActionPerformed(evt);
            }
        });

        jlbData.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlbData.setText("Data:");

        tfData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDataActionPerformed(evt);
            }
        });

        jbInserir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbInserir.setText("Inserir");
        jbInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInserirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jbInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jlbData)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfData, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jlbValor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfValor, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(36, Short.MAX_VALUE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbValor)
                    .addComponent(tfValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbData)
                    .addComponent(tfData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(jbInserir)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jblTiposDeDespesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rbDespesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlbTiposDeReceita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rbReceita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbDespesa)
                            .addComponent(rbReceita))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jblTiposDeDespesa)
                            .addComponent(jlbTiposDeReceita))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(204, 204, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), null));

        jlSaldoAtual.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlSaldoAtual.setText("Saldo Atual : R$ 00000,00");

        jlSaldoTotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlSaldoTotal.setText("Saldo Total : R$ 00000,00");

        jlData.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlData.setText("Data :");

        jbMudarNome.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jbMudarNome.setText("Mudar Nome");
        jbMudarNome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jbMudarNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMudarNomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlSaldoTotal)
                    .addComponent(jlSaldoAtual))
                .addGap(116, 116, 116)
                .addComponent(jlData)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jbMudarNome, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jbMudarNome, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jlSaldoAtual)
                        .addGap(18, 18, 18)
                        .addComponent(jlSaldoTotal)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jlData)
                        .addGap(40, 40, 40))))
        );

        jPanel5.setBackground(new java.awt.Color(204, 204, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), null));

        jLabel1.setText("By: Amanda Miranda Zanella, Bruno Henrique Wiedemann Reis, Lucas Miguel Vieira, Matheus Guilherme Jacinto");

        jbDespesas.setText("Despesas");
        jbDespesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDespesasActionPerformed(evt);
            }
        });

        jbReceitas.setText("Receitas");
        jbReceitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbReceitasActionPerformed(evt);
            }
        });

        jbReceitaDespesa.setText("Ordenar por data");
        jbReceitaDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbReceitaDespesaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbDespesas, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbReceitas, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbReceitaDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbReceitas)
                    .addComponent(jbDespesas)
                    .addComponent(jbReceitaDespesa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 5, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rbDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDespesaActionPerformed

        rbSalario.setEnabled(false);
        rbDecimo.setEnabled(false);
        rbFerias.setEnabled(false);
        rbOutrosR.setEnabled(false);

        rbAlimentacao.setEnabled(true);
        rbTransporte.setEnabled(true);
        rbResidencia.setEnabled(true);
        rbSaude.setEnabled(true);
        rbEducacao.setEnabled(true);
        rbEntretenimento.setEnabled(true);
        rbOutrosD.setEnabled(true);

// TODO add your handling code here:
    }//GEN-LAST:event_rbDespesaActionPerformed

    private void rbReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbReceitaActionPerformed
        // TODO add your handling code here:

        rbSalario.setEnabled(true);
        rbDecimo.setEnabled(true);
        rbFerias.setEnabled(true);
        rbOutrosR.setEnabled(true);

        rbAlimentacao.setEnabled(false);
        rbTransporte.setEnabled(false);
        rbResidencia.setEnabled(false);
        rbSaude.setEnabled(false);
        rbEducacao.setEnabled(false);
        rbEntretenimento.setEnabled(false);
        rbOutrosD.setEnabled(false);


    }//GEN-LAST:event_rbReceitaActionPerformed

    private void tfValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfValorActionPerformed

    private void tfDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDataActionPerformed

    private void rbAlimentacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAlimentacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbAlimentacaoActionPerformed

    private void jbInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInserirActionPerformed
        // TODO add your handling code here:

        try {
            String data = tfData.getText();//armazena o campo data
            DateTimeFormatter formatar = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            LocalDate date = LocalDate.parse(data, formatar);

            String tipoLancamento;

            if (rbDespesa.isSelected()) {

                tipoLancamento = "Despesa";
                Despesa d = new Despesa(tfValor.getText(), tipoDespesa(), date, tipoLancamento);

                control.incluirLancamento(d);

                adicionarValorTabela(d);

            } else if (rbReceita.isSelected()) {

                tipoLancamento = "Receita";

                Receita r = new Receita(tfValor.getText(), tipoReceita(), date, tipoLancamento);

                control.incluirLancamento(r);

                adicionarValorTabela(r);

            }

            NumberFormat nfBrasil = NumberFormat.getCurrencyInstance(new Locale("pt", "BR"));

            String saldoAtualFormatado = nfBrasil.format(control.calcularSaldo(true));
            String saldoTotalFormatado = nfBrasil.format(control.calcularSaldo(false));
            jlSaldoAtual.setText("Saldo Atual : " + saldoAtualFormatado);
            jlSaldoTotal.setText("Saldo Total : " + saldoTotalFormatado);

            tfValor.setText("");
            tfData.setText("");

        } catch (DateTimeParseException e) {
            JOptionPane.showMessageDialog(null, "O campo 'Data' está inválido, favor preencher corretamente.");
            return;
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "O campo 'Valor' está inválido, favor preencher corretamente.");
            return;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Não foi selecionado um tipo, favor selecionar um tipo.");
            return;

        }

    }//GEN-LAST:event_jbInserirActionPerformed

    private void jbDespesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDespesasActionPerformed
        // TODO add your handling code here:
        DespesaUI despesaUi = new DespesaUI(null, true);
        despesaUi.setControl(control);
        despesaUi.setVisible(true);

    }//GEN-LAST:event_jbDespesasActionPerformed

    private void jbReceitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbReceitasActionPerformed
        // TODO add your handling code here:
        ReceitaUI receitaUi = new ReceitaUI(null, true);
        receitaUi.setControl(control);
        receitaUi.setVisible(true);
    }//GEN-LAST:event_jbReceitasActionPerformed

    private void rbOutrosRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbOutrosRActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_rbOutrosRActionPerformed

    private void jbReceitaDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbReceitaDespesaActionPerformed
        // TODO add your handling code here:
        ((DefaultTableModel) jtTabela.getModel()).setRowCount(0);
        Collections.sort((List) (control.getExtrato()));
        for (Object o : control.getExtrato()) {
            adicionarValorTabela(o);
        }
    }//GEN-LAST:event_jbReceitaDespesaActionPerformed

    private void jbMudarNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMudarNomeActionPerformed
        // TODO add your handling code here:
        boolean validacao = false;
        PessoaUI pessoaUI = new PessoaUI(null, true);
        while (validacao == false) {

            pessoaUI.setVisible(true);

            Pessoa p = pessoaUI.getPessoa();
            if (p.getNome() == null) {

            } else {
                validacao = true;
                control.setPessoa(p);
            }
        }

        jlNome.setText("Controle financeiro de " + control.getPessoa().getNome());
    }//GEN-LAST:event_jbMudarNomeActionPerformed

    private void rbOutrosDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbOutrosDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbOutrosDActionPerformed

    DefaultTableCellRenderer tableCellRenderer = new DefaultTableCellRenderer() {

        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            Component comp = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
            Object ref = table.getValueAt(row, 2);
            //row : Linha genérica (vai retornar quantas linhas existe no JTable e valida uma por uma) 2 : valor do campo "valor"
            if (ref != null && (Float.parseFloat(ref.toString()) > 0)) {
                comp.setForeground(Color.green);
            } else if (ref != null && (Float.parseFloat(ref.toString()) == 0)) {
                comp.setForeground(Color.black);
            } else {
                comp.setForeground(Color.red);
            }
            return comp;
        }
    };

    /**
     *
     * @param lancamento
     */
    public void adicionarValorTabela(Object lancamento) {
        String dataFormatada;
        Object[] linha;
        linha = new Object[4];
        DateTimeFormatter formatarData = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        if (lancamento instanceof Receita) {
            linha[0] = ((Receita) lancamento).getTipoLancamento();//tipo lançamento
            linha[1] = ((Receita) lancamento).getTipoReceita().toString();//tipo Receita
            linha[2] = "+" + ((Receita) lancamento).getValor();//valor   
            jtTabela.setDefaultRenderer(Object.class, tableCellRenderer);
            dataFormatada = formatarData.format(((Receita) lancamento).getData());
            linha[3] = dataFormatada;//data
        } else {
            linha[0] = ((Despesa) lancamento).getTipoLancamento();//tipo lançamento
            linha[1] = ((Despesa) lancamento).getTipoDespesa().toString();
            linha[2] = "-" + ((Despesa) lancamento).getValor();//valor
            jtTabela.setDefaultRenderer(Object.class, tableCellRenderer);
            dataFormatada = formatarData.format(((Despesa) lancamento).getData());
            linha[3] = dataFormatada;//data            
        }
        DefaultTableModel model = (DefaultTableModel) jtTabela.getModel();
        model.addRow(linha);
    }

    /**
     *
     * @return
     */
    public TipoDespesa tipoDespesa() {
        if (rbAlimentacao.isSelected()) {
            return TipoDespesa.ALIMENTACAO;
        } else if (rbTransporte.isSelected()) {
            return TipoDespesa.TRANSPORTE;
        } else if (rbResidencia.isSelected()) {
            return TipoDespesa.RESIDENCIA;
        } else if (rbSaude.isSelected()) {
            return TipoDespesa.SAUDE;
        } else if (rbEntretenimento.isSelected()) {
            return TipoDespesa.ENTRETENIMENTO;
        } else if (rbOutrosD.isSelected()) {
            return TipoDespesa.OUTRAS;
        } else if (rbEducacao.isSelected()) {
            return TipoDespesa.EDUCACAO;
        } else {
            return null;
        }

    }

    /**
     *
     * @return
     */
    public TipoReceita tipoReceita() {
        if (rbSalario.isSelected()) {
            return TipoReceita.SALARIO;
        } else if (rbDecimo.isSelected()) {
            return TipoReceita.DECIMO_TERCEIRO;
        } else if (rbFerias.isSelected()) {
            return TipoReceita.FERIAS;
        } else if (rbOutrosR.isSelected()) {
            return TipoReceita.OUTRAS;
        } else {
            return null;
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ControleFinanceiroUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ControleFinanceiroUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ControleFinanceiroUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ControleFinanceiroUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ControleFinanceiroUI().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup brgpTipoDespesa;
    private javax.swing.ButtonGroup brgpTipoReceita;
    private javax.swing.ButtonGroup btgpTipoControle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbDespesas;
    private javax.swing.JButton jbInserir;
    private javax.swing.JButton jbMudarNome;
    private javax.swing.JButton jbReceitaDespesa;
    private javax.swing.JButton jbReceitas;
    private javax.swing.JLabel jblTiposDeDespesa;
    private javax.swing.JLabel jlData;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlSaldoAtual;
    private javax.swing.JLabel jlSaldoTotal;
    private javax.swing.JLabel jlbData;
    private javax.swing.JLabel jlbTiposDeReceita;
    private javax.swing.JLabel jlbValor;
    private javax.swing.JTable jtTabela;
    private javax.swing.JRadioButton rbAlimentacao;
    private javax.swing.JRadioButton rbDecimo;
    private javax.swing.JRadioButton rbDespesa;
    private javax.swing.JRadioButton rbEducacao;
    private javax.swing.JRadioButton rbEntretenimento;
    private javax.swing.JRadioButton rbFerias;
    private javax.swing.JRadioButton rbOutrosD;
    private javax.swing.JRadioButton rbOutrosR;
    private javax.swing.JRadioButton rbReceita;
    private javax.swing.JRadioButton rbResidencia;
    private javax.swing.JRadioButton rbSalario;
    private javax.swing.JRadioButton rbSaude;
    private javax.swing.JRadioButton rbTransporte;
    private javax.swing.JFormattedTextField tfData;
    private javax.swing.JTextField tfValor;
    // End of variables declaration//GEN-END:variables
}
